# Generated by Django 4.2.7 on 2025-04-25 09:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True, verbose_name='Номер партии')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('defect_count', models.IntegerField(default=0, verbose_name='Количество брака')),
                ('total_count', models.IntegerField(default=0, verbose_name='Общее количество')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название настройки')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('pressure', models.FloatField(verbose_name='Давление')),
                ('mixing_speed', models.FloatField(verbose_name='Скорость перемешивания')),
                ('glazing_thickness', models.FloatField(verbose_name='Толщина глазури')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Настройка производства',
                'verbose_name_plural': 'Настройки производства',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('notification_type', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('success', 'Успех')], default='info', max_length=20, verbose_name='Тип уведомления')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время уведомления')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.batch', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BatchParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('pressure', models.FloatField(verbose_name='Давление')),
                ('mixing_speed', models.FloatField(verbose_name='Скорость перемешивания')),
                ('glazing_thickness', models.FloatField(verbose_name='Толщина глазури')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время измерения')),
                ('is_defect', models.BooleanField(default=False, verbose_name='Является браком')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='api.batch', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Параметр партии',
                'verbose_name_plural': 'Параметры партии',
                'ordering': ['-timestamp'],
            },
        ),
    ]
