# Generated by Django 4.2.7 on 2025-04-28 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerVisionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.TextField(blank=True, null=True, verbose_name='Путь к изображению')),
                ('detected_objects', models.JSONField(default=dict, verbose_name='Обнаруженные объекты')),
                ('confidence_score', models.FloatField(default=0.0, verbose_name='Оценка достоверности')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время фиксации')),
                ('is_defect', models.BooleanField(default=False, verbose_name='Обнаружен дефект')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_data', to='api.batch', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Данные компьютерного зрения',
                'verbose_name_plural': 'Данные компьютерного зрения',
                'ordering': ['-timestamp'],
            },
        ),
    ]
